export const SET_INPUT_URL = 'SET_INPUT_URL';

export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_FAILED = 'FETCH_ARTICLES_FAILED';
